using Application.Common.Interfaces;
using Application.Features.Auth;
using Application.Features.Auth.Register;
using Application.Test.Helpers;
using Domain.ApplicationUserAggregate;
using Domain.AuthUserAggregate;
using Microsoft.AspNetCore.Identity;
using NSubstitute;
using Shared.Constants;
using Shared.Results;

namespace Application.Test.Features.Auth.Register;

public class RegisterHandlerTests
{
    private readonly IUnitOfWork _unitOfWork;
    private readonly ITokenProvider _tokenProvider;
    private readonly IApplicationDatabaseContext _identityDbContext;

    public RegisterHandlerTests()
    {
        _unitOfWork = TestHelpers.CreateMockUnitOfWork();
        _tokenProvider = Substitute.For<ITokenProvider>();
        _identityDbContext = Substitute.For<IApplicationDatabaseContext>();
    }

    [Fact]
    public async Task Handle_ValidInput_CreatesUserAndReturnsSuccess()
    {
        // Arrange
        var command = new RegisterCommand
        {
            FirstName = "John",
            LastName = "Doe",
            Email = "newuser@test.com",
            Password = "Password123!",
            DateOfBirth = new DateTime(1990, 1, 1),
            Gender = Gender.Male,
            CityId = 1
        };

        var userManager = UserManagerTestHelper.CreateUserManagerWithUsers([], [new IdentityRole { Name = RolesNameValues.User, NormalizedName = RolesNameValues.User.ToUpper() }]);

        _unitOfWork.CommitAsync(Arg.Any<CancellationToken>()).Returns(1);

        _tokenProvider.CreateAccessToken(Arg.Any<TokenRequest>()).Returns("access-token");

        // Note: The actual user ID will be generated by UserManager.CreateAsync
        // We'll need to get it from the created user
        var refreshToken = new RefreshToken
        {
            UserId = "identity-1", // This will be the actual ID from CreateAsync
            Token = "refresh-token",
            ExpiresAtUtc = DateTime.UtcNow.AddDays(7)
        };
        _tokenProvider.CreateRefreshToken(Arg.Any<string>()).Returns(refreshToken);
        _identityDbContext.SaveChangesAsync(Arg.Any<CancellationToken>()).Returns(1);

        var handler = new RegisterHandler(_unitOfWork, userManager, _tokenProvider, _identityDbContext);

        // Act
        var result = await handler.Handle(command, CancellationToken.None);

        // Assert
        Assert.True(result.IsSuccess);
        Assert.NotNull(result.Value);
        Assert.Equal("access-token", result.Value.Token);
        Assert.Equal(ResultStatus.Created, result.Status);
    }

    [Fact]
    public async Task Handle_EmailAlreadyExists_ReturnsError()
    {
        // Arrange
        var command = new RegisterCommand
        {
            FirstName = "John",
            LastName = "Doe",
            Email = "existing@test.com",
            Password = "Password123!",
            DateOfBirth = new DateTime(1990, 1, 1),
            Gender = Gender.Male,
            CityId = 1
        };

        // Create UserManager with existing user
        var existingUser = new IdentityUser { Email = command.Email, UserName = command.Email };
        var userManager = UserManagerTestHelper.CreateUserManagerWithUsers([existingUser]);

        var handler = new RegisterHandler(_unitOfWork, userManager, _tokenProvider, _identityDbContext);

        // Act
        var result = await handler.Handle(command, CancellationToken.None);

        // Assert
        Assert.False(result.IsSuccess);
        Assert.Single(result.Errors);
        Assert.Contains("Email is already taken", result.Errors.First());
    }
}

